# Generated by Django 4.0.3 on 2022-04-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
